"""Pydantic schemas for data validation across agent boundaries."""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class UserRequirement(BaseModel):
    """Initial requirement input from user."""

    raw_text: str = Field(description="Raw requirement text submitted by user")
    context: Optional[str] = Field(
        default=None, description="Optional domain context or architectural constraints"
    )


class RequirementSpec(BaseModel):
    """Detailed technical specifications generated by Requirements Agent."""

    application_name: str = Field(
        description="Name of the application or module to build"
    )
    problem_statement: str = Field(
        description="Clear definition of the problem being solved and core value proposition"
    )
    functional_requirements: List[str] = Field(
        description="Explicit functional capabilities, features, and behaviors"
    )
    non_functional_requirements: List[str] = Field(
        description="Performance, security, maintainability, and quality standards"
    )
    api_requirements: List[str] = Field(
        description="API endpoints, public methods, input parameters, and return types"
    )
    data_requirements: List[str] = Field(
        description="Data schemas, state structures, storage formats, or entity models"
    )
    assumptions: List[str] = Field(
        description="Key architectural, environment, or scope assumptions made"
    )
    acceptance_criteria: List[str] = Field(
        description="Verifiable test criteria to validate successful build"
    )


class ArchitecturePlan(BaseModel):
    """Architectural blueprint produced by Architecture Agent."""

    architecture_style: str = Field(description="High-level architectural pattern or style (e.g. Modular Monolith, Layered)")
    components: List[str] = Field(description="List of key architectural components or modules")
    technology_choices: List[str] = Field(description="Selected frameworks, libraries, runtime environments, or tools")
    api_design: str = Field(description="High-level specification of API interface design and structure")
    data_flow: str = Field(description="Description of data movement, inputs/outputs, and processing pipeline")
    design_decisions: List[str] = Field(description="Key design choices and architectural trade-offs made")
    risks: List[str] = Field(description="Identified technical or architectural risks")
    recommendations: List[str] = Field(description="Actionable recommendations for Builder Agent")


class SecurityAssessment(BaseModel):
    """Security assessment report produced by Security Agent."""

    security_status: str = Field(description="Overall security status indicator (e.g. SAFE, NEEDS_REVIEW, CRITICAL)")
    threats: List[str] = Field(description="Identified threat vectors or security attack risks")
    input_validation: str = Field(description="Strategy for sanitization, input validation, and boundary checking")
    authentication: str = Field(description="Authentication strategy or requirement (if applicable)")
    authorization: str = Field(description="Authorization / access control strategy (if applicable)")
    data_protection: str = Field(description="Data encryption, privacy, and sensitive data protection measures")
    vulnerabilities: List[str] = Field(description="Potential security vulnerabilities or OWASP risks")
    recommendations: List[str] = Field(description="Security recommendations and hardening steps for implementation")


class TestStrategy(BaseModel):
    """Comprehensive test strategy produced by Test Strategy Agent."""

    __test__ = False

    test_strategy: str = Field(description="Overall testing approach and philosophy")
    functional_tests: List[str] = Field(description="Functional test scenarios to validate business logic")
    api_tests: List[str] = Field(description="API interface and boundary test cases")
    edge_cases: List[str] = Field(description="Boundary condition, extreme value, and edge case test scenarios")
    negative_tests: List[str] = Field(description="Negative test cases, exception handling, and invalid inputs")
    non_functional_tests: List[str] = Field(description="Performance, stress, or maintainability test considerations")
    acceptance_criteria_mapping: List[str] = Field(description="Explicit mapping of test strategy to requirement acceptance criteria")



class StructuredRequirements(BaseModel):
    """Parsed and refined requirements from Requirements Agent."""

    title: str = Field(description="Short summary of target software artifact")
    features: List[str] = Field(description="List of specific functional requirements")
    constraints: List[str] = Field(description="Technical or environment constraints")
    acceptance_criteria: List[str] = Field(
        description="Conditions required to validate successful build"
    )


class GeneratedFile(BaseModel):
    """Represents a generated source code or test file."""

    path: str = Field(description="Relative file path of the generated file (e.g. app/calculator.py, tests/test_calculator.py)")
    content: str = Field(description="Complete source code or text content of the file")
    purpose: str = Field(description="Short description of what this file contains or does")


class ImplementationSummary(BaseModel):
    """Summary of the implementation decisions and technical design."""

    overview: str = Field(description="High-level description of the technical implementation approach")
    components: List[str] = Field(description="List of key modules or components created")
    key_decisions: List[str] = Field(description="Key design, architectural, or algorithm decisions made")


class BuildResult(BaseModel):
    """Structured output generated by the Builder Agent."""

    status: str = Field(default="SUCCESS", description="Build status indicator, e.g. SUCCESS or FAILED")
    files: List[GeneratedFile] = Field(description="List of generated application source files and test files")
    implementation_summary: ImplementationSummary = Field(description="High-level implementation and design summary")
    assumptions: List[str] = Field(description="Assumptions made during code generation")
    potential_risks: List[str] = Field(description="Potential risks, edge cases, or performance limitations")


class CodeArtifact(BaseModel):
    """Generated code artifact from Builder Agent."""

    filename: str = Field(description="Target relative filepath for generated code")
    content: str = Field(description="Source code or text content of generated artifact")
    language: str = Field(default="python", description="Programming language of content")


class TestCase(BaseModel):
    """Independently derived test case definition."""

    __test__ = False

    id: str = Field(description="Unique test identifier (e.g. TC-001)")
    requirement: str = Field(description="Target requirement text or criterion being evaluated")
    description: str = Field(description="Description of test scenario")
    test_type: str = Field(description="Category of test: functional, api, non_functional, edge_case, invalid_input")
    expected_result: str = Field(description="Expected behavior or return value")


class TestExecution(BaseModel):
    """Execution output/evaluation for a specific test case."""

    __test__ = False

    test_case_id: str = Field(description="ID of corresponding test case")
    status: str = Field(description="Status of evaluation: PASSED, FAILED, or SKIPPED")
    actual_result: str = Field(description="Observed behavior or result from static evaluation")
    error: Optional[str] = Field(default="", description="Error details or failure reason if failed")


class TestResult(BaseModel):
    """Comprehensive output generated by Test Agent."""

    __test__ = False

    status: str = Field(description="Overall test suite status: PASSED or FAILED")
    test_cases: List[TestCase] = Field(description="List of independently derived test cases")
    executions: List[TestExecution] = Field(description="List of test execution results")
    passed_count: int = Field(default=0, description="Count of passed test cases")
    failed_count: int = Field(default=0, description="Count of failed test cases")
    coverage_summary: str = Field(description="Summary of requirement coverage")
    issues: List[str] = Field(description="List of issues or unfulfilled requirements identified")
    recommendations: List[str] = Field(description="Recommendations for fixing failed tests or improving code")


class ValidationResult(BaseModel):
    """Final assessment report from Validation Agent acting as quality gate."""

    __test__ = False

    status: str = Field(description="Overall validation status: PASS or FAIL")
    overall_score: float = Field(default=0.0, description="Overall compliance score between 0.0 and 1.0")
    requirements_coverage: float = Field(default=0.0, description="Percentage of requirements satisfied (0.0 to 1.0)")
    functional_assessment: str = Field(description="Evaluation of functional completeness and behavior")
    test_assessment: str = Field(description="Evaluation of test coverage and test execution results")
    architecture_assessment: str = Field(description="Evaluation of architectural design, modularity, and structure")
    security_assessment: str = Field(description="Evaluation of code safety, input validation, and security risks")
    issues: List[str] = Field(description="List of defects, missing features, or security problems identified")
    recommendations: List[str] = Field(description="Actionable recommendations for Builder Agent to improve code")
    failed_requirements: List[str] = Field(description="Explicit list of requirements that failed validation")
    approval_reason: str = Field(description="Explanation for PASS verdict or summary reason for FAIL verdict")


class ValidationReport(BaseModel):
    """Final assessment report from Validation Agent."""

    verdict: Literal["PASS", "FAIL"] = Field(
        description="Overall verdict of build and verification"
    )
    score: float = Field(
        default=0.0, description="Quality/compliance score between 0.0 and 1.0"
    )
    feedback: str = Field(
        description="Detailed feedback for user or for Builder agent retry"
    )
    retry_suggested: bool = Field(
        default=False, description="Indicates if Builder should attempt code revision"
    )
