"""State definition for LangGraph orchestration."""

from typing import List, Dict, Any, Optional, TypedDict


class AgentState(TypedDict, total=False):
    """Global state container passed between LangGraph nodes."""

    # Raw user input requirement
    user_requirement: str

    # Structured representation produced by Requirements Agent
    structured_requirements: Optional[Dict[str, Any]]

    # Structured build result produced by Builder Agent
    build_result: Optional[Dict[str, Any]]

    # Generated code artifacts produced by Builder Agent
    code_artifacts: List[Dict[str, Any]]

    # Structured test result generated by Test Agent
    test_result: Optional[Dict[str, Any]]

    # Test outputs generated by Test Agent
    test_results: List[Dict[str, Any]]

    # Structured validation result generated by Validation Agent
    validation_result: Optional[Dict[str, Any]]

    # Overall validation verdict and feedback from Validation Agent
    validation_report: Optional[Dict[str, Any]]

    # Iteration tracking for builder retry loop
    iteration_count: int

    # Maximum iterations allowed before terminating retry loop
    max_iterations: int

    # Counter for builder retries
    retry_count: int

    # Max retries allowed before terminating with failure
    max_retries: int

    # Message logs / agent conversation history
    logs: List[str]
